FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["NotificationApp/NotificationApp.csproj", "NotificationApp/"]
RUN dotnet restore "NotificationApp/NotificationApp.csproj"
COPY . .
WORKDIR "/src/NotificationApp"
RUN dotnet build "NotificationApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NotificationApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NotificationApp.dll"]
